# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-ClamAV
version:      0.01
version_from: lib/Catalyst/Plugin/ClamAV.pm
installdirs:  site
requires:
    Catalyst:                      0
    ClamAV::Client:                0.1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
